
(:WIDTH 40 :HEIGHT 15 :TILES
 ((:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :SPAWN :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY)
  (:EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :GROUND :EMPTY :STEEL :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY)
  (:EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS :CONTACTS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY
   :GROUND :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :STEEL :STEEL :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS
   :EMPTY :EMPTY :EMPTY :GROUND :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :STEEL :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :STEEL :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :GROUND
   :GROUND :GROUND :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :GROUND :CONTACTS :GROUND :GROUND :GROUND
   :GROUND :GROUND :GROUND :GROUND :GROUND :GROUND :GROUND :EMPTY :EMPTY :STEEL
   :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :CONTACTS :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY))) 