
(:WIDTH 40 :HEIGHT 30 :TILE-SIZE 24 :META
 (:NAME "Yeni Level" :LEMMINGS-TOTAL 101 :LEMMINGS-REQUIRED 101 :TIME-LIMIT-SEC
  3001)
 :TILES
 ((:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :CONTACTS :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EXIT :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EMPTY :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :STEEL :EMPTY :SPAWN :EMPTY :EMPTY :EMPTY :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :SPAWN :EMPTY :EMPTY :EMPTY :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EXIT :EXIT :EXIT :EXIT :EXIT :EXIT :EXIT
   :EXIT :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :SPAWN :EMPTY :EMPTY :EMPTY :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :SPAWN :EMPTY :EMPTY :EMPTY :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :SPAWN :EMPTY :EMPTY :EMPTY :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EXIT :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :EMPTY :EMPTY :EMPTY
   :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY))) 