
(:WIDTH 40 :HEIGHT 30 :TILE-SIZE 24 :META
 (:NAME "Yeni Level" :LEMMINGS-TOTAL 1000 :LEMMINGS-REQUIRED 1000
  :TIME-LIMIT-SEC 30000)
 :TILES
 ((:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :STEEL
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS
   :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL
   :STEEL :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :CONTACTS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EXIT :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :GROUND :GROUND :GROUND :GROUND :GROUND :GROUND
   :GROUND :GROUND :GROUND :GROUND :GROUND :GROUND :GROUND :EMPTY :STEEL
   :GROUND :GROUND :GROUND :GROUND :CAN-BE-EXCAVATED :CONTACTS
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY
   :EMPTY :CONTACTS :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY
   :CONTACTS :CONTACTS :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY :EMPTY
   :CONTACTS :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED :CAN-BE-EXCAVATED
   :CAN-BE-EXCAVATED :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY)
  (:EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :EMPTY :EMPTY
   :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL
   :STEEL :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :STEEL :STEEL :CONTACTS
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :SPAWN :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :CONTACTS :EMPTY :EMPTY :EMPTY
   :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :DECORATIONS-AND-BACKGROUND-ANIMS
   :DECORATIONS-AND-BACKGROUND-ANIMS :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY)
  (:EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY
   :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY :EMPTY))) 